apiVersion: v1
kind: Service
metadata:
  labels:
    app: oai-ue
  name: oai-ue
spec:
  type: ClusterIP
  ports:
  - name: if-s1
    port: 38412
    protocol: SCTP
    targetPort: 38412
  - name: if-s1u
    port: 2152
    protocol: UDP
    targetPort: 2152
  selector:
    app: oai-ue
