apiVersion: apps/v1
kind: Deployment
metadata:
  name: open5gs-srsue
  labels:
    app: open5gs-srsue
    # sliceidx: 6d3d79da-f781-4cd9-813a-dbdad01e01c0
  annotations:
    free5gc.org/nssi-id: '27394d25-dbf5-428e-8fc3-f5b2add67115'
    free5gc.org/nsi-ids: '[
        { "id": "4e6db941-47d6-4fce-9c71-f7eb35a75d03" },
    ]'
    free5gc.org/supported-snssais: '[
        { "st": 1,
          "ssd": "010203",
        },
        { "st": 1,
          "ssd": "112233",
        },
    ]'
spec:
  replicas: 1
  selector:
    matchLabels:
      app: open5gs-srsue
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: open5gs-srsue
      annotations:
        k8s.v1.cni.cncf.io/networks: open5gs-srsue2, open5gs-srsue3
    spec:
      securityContext:
        runAsUser: 0
        runAsGroup: 0
      containers:
        - name: open5gs-srsue
          image: monandkey/gnbsim:latest
          imagePullPolicy: IfNotPresent
          # imagePullPolicy: Always
          command: ["sh"]
          tty: true
          securityContext:
            privileged: true
            capabilities:
              add: ["NET_ADMIN", "SYS_TIME"]
          volumeMounts:
            - name: open5gs-srsue-config
              mountPath: /gnbsim/config/
            - mountPath: /dev/net/tun
              name: tun-devdir
          ports:
            - containerPort: 38412
              name: if-n1n2
              protocol: SCTP
            - containerPort: 2152
              name: if-n3
              protocol: UDP
        - name: open5gs-srsue-probe
          image: nginx:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
              name: http-probe
              protocol: TCP
        - name: tcpdump
          image: mobilecore/tcpdump:latest
          imagePullPolicy: IfNotPresent
          command:
            - /bin/sleep
            - infinity
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      serviceAccountName: open5gs-srsue-sa
      terminationGracePeriodSeconds: 30
      volumes:
        - name: open5gs-srsue-config
          configMap:
            name: open5gs-srsue-config
        - name: tun-devdir
          hostPath:
            path: /dev/net/tun