apiVersion: apps/v1
kind: Deployment
metadata:
  name: open5gs-ue
  labels:
    app: open5gs-ue
spec:
  replicas: 1
  selector:
    matchLabels:
      app: open5gs-ue
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: open5gs-ue
      annotations:
        k8s.v1.cni.cncf.io/networks: open5gs-ue-n1n2
    spec:
      securityContext:
        runAsUser: 0
        runAsGroup: 0
      containers: 
      - name: open5gs-ue
        imagePullPolicy: IfNotPresent
        image: shubhamtatvamasi/srsran-demo:0.2.1
        securityContext:    
         privileged: false
         capabilities:
          add: ["NET_ADMIN", "SYS_NICE"]
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        tty: true
        command: ["/bin/bash"]
        # args:
          # - srsue
          # - --usim.algo=milenage
          # - --usim.opc=63BFA50EE6523365FF14C1F45F88737D
          # - --rf.device_name=zmq
          # - --rf.device_args="tx_port=tcp://*:2001,rx_port=tcp://localhost:2000,id=ue,base_srate=23.04e6"
        volumeMounts:
        - name: tun-volume
          mountPath: /dev/net/tun
        ports:
          - name: if-n1n2
            containerPort: 38412
            protocol: SCTP
          - name: if-n3
            containerPort: 2152
            protocol: UDP
      - name: tcpdump
        image: mobilecore/tcpdump:latest
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        command:
          - /bin/sleep
          - infinity
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      serviceAccountName: open5gs-ue-sa
      terminationGracePeriodSeconds: 30
      volumes:
      - name: tun-volume
        hostPath:
          path: /dev/net/tun
