apiVersion: apps/v1
kind: Deployment
metadata:
  name: open5gs-pgw
  labels:
    app: open5gs-pgw
spec:
  replicas: 1
  selector:
    matchLabels:
      app: open5gs-pgw
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: open5gs-pgw
      annotations:
        k8s.v1.cni.cncf.io/networks: open5gs-pgw-s5c-gx, open5gs-pgw-s5u
    spec:
      securityContext:
        runAsUser: 0
        runAsGroup: 0
      containers:
        - name: open5gs-pgw
          image: registry.gitlab.com/infinitydon/registry/open5gs-aio:v1.2.0
          imagePullPolicy: IfNotPresent
          command: ["/bin/sh", "-c"]
          args:
            - ip tuntap add name ogstun mode tun;
              ip addr add 45.45.0.1/16 dev ogstun;
              sysctl -w net.ipv6.conf.all.disable_ipv6=0;
              ip addr add cafe::1/64 dev ogstun;
              ip link set ogstun up;
              sh -c "echo 1 > /proc/sys/net/ipv4/ip_forward";
              iptables -t nat -A POSTROUTING -s 45.45.0.0/16 ! -o ogstun -j MASQUERADE;
              open5gs-pgwd -c /open5gs/config-map/pgw.yaml;
          securityContext:
            privileged: true
            capabilities:
              add: ["NET_ADMIN"]
          volumeMounts:
            - name: open5gs-pgw-config
              mountPath: /open5gs/config-map/pgw.yaml
              subPath: "pgw.yaml"
            - name: open5gs-pgw-diameter
              mountPath: /open5gs/config-map/diameter-pgw.conf
              subPath: "diameter-pgw.conf"
            - mountPath: /dev/net/tun
              name: dev-net-tun
          ports:
            - name: if-s5c
              containerPort: 2123
              protocol: UDP
            - name: if-s5u
              containerPort: 2125
              protocol: UDP
            - name: if-gx
              containerPort: 3868
              protocol: TCP
        - name: tcpdump
          image: mobilecore/tcpdump:latest
          imagePullPolicy: IfNotPresent
          command:
            - /bin/sleep
            - infinity
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      serviceAccountName: open5gs-pgw-sa
      terminationGracePeriodSeconds: 30
      volumes:
        - name: open5gs-pgw-config
          configMap:
            name: open5gs-pgw-config
        - name: open5gs-pgw-diameter
          configMap:
            name: open5gs-pgw-diameter
        - name: dev-net-tun
          hostPath:
            path: /dev/net/tun
