apiVersion: apps/v1
kind: Deployment
metadata:
  name: open5gs-hss
  labels:
    app: open5gs-hss
spec:
  replicas: 1
  selector:
    matchLabels:
      app: open5gs-hss
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: open5gs-hss
      annotations:
        k8s.v1.cni.cncf.io/networks: open5gs-hss-s6a
        cni.projectcalico.org/ipAddrs: "[\"10.244.254.34\"]"
    spec:
      securityContext:
        runAsUser: 0
        runAsGroup: 0
      containers:
        - name: open5gs-hss
          image: registry.gitlab.com/infinitydon/registry/open5gs-aio:v1.2.0
          imagePullPolicy: IfNotPresent
          command: ["open5gs-hssd", "-c", "/open5gs/config-map/hss.yaml"]
          securityContext:
            privileged: false
          volumeMounts:
            - name: open5gs-hss-config
              mountPath: /open5gs/config-map/hss.yaml
              subPath: "hss.yaml"
            - name: open5gs-hss-diameter
              mountPath: /open5gs/config-map/diameter-hss.conf
              subPath: "diameter-hss.conf"
          ports:
            - name: if-s6a
              containerPort: 3868
              protocol: SCTP
        - name: tcpdump
          image: mobilecore/tcpdump:latest
          imagePullPolicy: IfNotPresent
          command:
            - /bin/sleep
            - infinity
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      serviceAccountName: open5gs-hss-sa
      terminationGracePeriodSeconds: 30
      volumes:
        - name: open5gs-hss-config
          configMap:
            name: open5gs-hss-config
        - name: open5gs-hss-diameter
          configMap:
            name: open5gs-hss-diameter
