---
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition 
metadata:
  name: f5gc-smf-n4
spec:
  config: '{ 
      "cniVersion": "0.3.1",
      "type": "ipvlan",
      "capabilities": { "ips": true },
      "master": "eth1",
      "mode": "l2",
      "ipam": {
        "type": "static",
        "addresses": [
                {
                        "address": "172.16.30.20/24",
                        "gateway": "172.16.30.1"
                }
        ]
      }
    }'
