apiVersion: v1
kind: ConfigMap
metadata:
  name: srsenb-configmap
data: 
  enb.conf: |
    [enb]
    enb_id = 0x19B
    cell_id = 0x01
    phy_cell_id = 1
    tac = 0x0007
    mcc = 001
    mnc = 01
    mme_addr = 172.16.10.120
    gtp_bind_addr = 172.16.50.30
    s1c_bind_addr = 172.16.10.100
    n_prb = 25
    [enb_files]
    sib_config = sib.mbsfn.conf
    rr_config  = rr.conf
    drb_config = drb.conf
    [rf]
    dl_earfcn = 3400
    tx_gain = 80
    rx_gain = 40
    device_name = shmemrf
    device_args = enb
    time_adv_nsamples = 0
    burst_preamble_us = 0
    [pcap]
    enable = false
    filename = /tmp/enb.pcap
    [log]
    all_level = warn
    phy_level = warn
    phy_lib_level = warn
    all_hex_limit = 32
    filename = enb.log
    file_max_size = -1
    [gui]
    enable = false
    [scheduler]
    pusch_max_mcs    = 16
    nof_ctrl_symbols = 3
    [expert]
    nof_phy_threads       = 1
    enable_mbsfn = true
    [rf_calibration]
  rr.conf: |
    mac_cnfg =
    {
      phr_cnfg =
      {
        dl_pathloss_change = "3dB"; // Valid: 1, 3, 6 or INFINITY
        periodic_phr_timer = 50;
        prohibit_phr_timer = 0;
      };
      ulsch_cnfg =
      {
        max_harq_tx = 4;
        periodic_bsr_timer = 20; // in ms
        retx_bsr_timer = 320;   // in ms
      };
      time_alignment_timer = -1; // -1 is infinity
    };
    phy_cnfg =
    {
      phich_cnfg =
      {
        duration  = "Normal";
        resources = "1/6";
      };
      pusch_cnfg_ded =
      {
        beta_offset_ack_idx = 6;
        beta_offset_ri_idx  = 6;
        beta_offset_cqi_idx = 6;
      };
      sched_request_cnfg =
      {
        dsr_trans_max = 64;
        period = 20;       // in ms
        subframe = [1];    // vector of subframe indices allowed for SR transmissions
        nof_prb = 2;       // number of PRBs on each extreme used for SR (total prb is twice this number)
      };
      cqi_report_cnfg =
      {
        mode = "periodic";
        simultaneousAckCQI = true;
        period = 40; // in ms
        subframe = [0];
        nof_prb = 2;
      };
    };
  sib.conf: |
    sib1 =
    {
        intra_freq_reselection = "Allowed";
        q_rx_lev_min = -130;
        //p_max = 3;
        cell_barred = "Not Barred"
        si_window_length = 20;
        sched_info =
        (
            {
                si_periodicity = 16;
                si_mapping_info = []; // comma-separated array of SIB-indexes (from 3 to 13). Leave empty or commented to just scheduler sib2
            }
        );
        system_info_value_tag = 0;
    };
    sib2 =
    {
        rr_config_common_sib =
        {
            rach_cnfg =
            {
                num_ra_preambles = 52;
                preamble_init_rx_target_pwr = -104;
                pwr_ramping_step = 6;  // in dB
                preamble_trans_max = 10;
                ra_resp_win_size = 10;  // in ms
                mac_con_res_timer = 64; // in ms
                max_harq_msg3_tx = 4;
            };
            bcch_cnfg =
            {
                modification_period_coeff = 16; // in ms
            };
            pcch_cnfg =
            {
                default_paging_cycle = 32; // in rf
                nB = "1";
            };
            prach_cnfg =
            {
                root_sequence_index = 128;
                prach_cnfg_info =
                {
                    high_speed_flag = false;
                    prach_config_index = 3;
                    prach_freq_offset = 2;
                    zero_correlation_zone_config = 5;
                };
            };
            pdsch_cnfg =
            {
                p_b = 0;
                rs_power = 0;
            };
            pusch_cnfg =
            {
                n_sb = 1;
                hopping_mode = "inter-subframe";
                pusch_hopping_offset = 2;
                enable_64_qam = false; // 64QAM PUSCH is not currently enabled
                ul_rs =
                {
                    cyclic_shift = 0;
                    group_assignment_pusch = 0;
                    group_hopping_enabled = false;
                    sequence_hopping_enabled = false;
                };
            };
            pucch_cnfg =
            {
                delta_pucch_shift = 2;
                n_rb_cqi = 2;
                n_cs_an = 0;
                n1_pucch_an = 12;
            };
            ul_pwr_ctrl =
            {
                p0_nominal_pusch = -85;
                alpha = 0.7;
                p0_nominal_pucch = -107;
                delta_flist_pucch =
                {
                    format_1  = 0;
                    format_1b = 3;
                    format_2  = 1;
                    format_2a = 2;
                    format_2b = 2;
                };
                delta_preamble_msg3 = 8;
            };
            ul_cp_length = "Normal";
        };
        ue_timers_and_constants =
        {
            t300 = 2000; // in ms
            t301 = 100;  // in ms
            t310 = 1000; // in ms
            n310 = 1;
            t311 = 1000; // in ms
            n311 = 1;
        };
        freqInfo =
        {
            ul_carrier_freq_present = true;
            ul_bw_present = true;
            additional_spectrum_emission = 1;
        };
        time_alignment_timer = "INFINITY"; // use "sf500", "sf750", etc.
    };

