apiVersion: v1
kind: Service
metadata:
  name: free5gc-smf-svc-pool
  namespace: free5gc
  labels:
    epc-mode: smf
spec:
  selector:
    app: free5gc-smf
  ports:
  - protocol: TCP
    targetPort: 29510
    port: 29502
  selector:
    epc-mode: smf
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: StatefulSet
metadata:
  name: free5gc-smf-deployment
  annotations:
    "cni.projectcalico.org/ipAddrs": "[\"10.244.1.2\"]"
  namespace: free5gc
  labels:
    epc-mode: smf
spec:
  replicas: 1
  serviceName: "free5gc-smf-svc-pool"
  selector:
    matchLabels:
      epc-mode: smf
  template:
    metadata:
      labels:
        epc-mode: smf
    spec:
      containers:
        - name: smf
          image: monandkey/free5gc-smf:3.0.4
          imagePullPolicy: IfNotPresent
          command: ["./smf"]
          volumeMounts:
          - name: free5gc-smf-config
            mountPath: /free5gc/config-map/smfcfg.conf
            subPath: "smfcfg.conf"
          - name: free5gc-smf-free5gc-config
            mountPath: /free5gc/config-map/free5gc.conf
            subPath: "free5gc.conf"
      volumes:
        - name: free5gc-smf-config
          configMap:
            name: free5gc-smf-config
        - name: free5gc-smf-free5gc-config
          configMap:
            name: free5gc-smf-free5gc-config