apiVersion: apps/v1
kind: Deployment
metadata:
  name: f5gc-upf
  labels:
    app: f5gc-upf
    sliceidx: 6d3d79da-f781-4cd9-813a-dbdad01e01c0
  annotations:
    free5gc.org/nssi-id: '27394d25-dbf5-428e-8fc3-f5b2add67115'
    free5gc.org/nsi-ids: '[
        { "id": "4e6db941-47d6-4fce-9c71-f7eb35a75d03" },
    ]'
spec:
  replicas: 1
  selector:
    matchLabels:
      app: f5gc-upf
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: f5gc-upf
      annotations:
        k8s.v1.cni.cncf.io/networks: f5gc-upf-n3, f5gc-upf-n4, f5gc-upf-n6-n9
        cni.projectcalico.org/ipAddrs: "[\"10.244.254.6\"]"
    spec:
      securityContext:
        runAsUser: 0
        runAsGroup: 0
      containers:
        - name: f5gc-upf
          image: mobilecore/free5gc-upf:3.0.4-1
          imagePullPolicy: IfNotPresent
          command: ["/bin/bash", "-c"]
          args:
            - /sbin/sysctl -w net.ipv4.ip_forward=1;
              iptables -t nat -vL;
              iptables -t nat -A POSTROUTING -s 172.16.1.0/24 ! -o net3 -j MASQUERADE;
              /free5gc/free5gc-upfd/free5gc-upfd -f /free5gc/config/upfcfg.yaml;
          securityContext:
            privileged: true
            capabilities:
              add: ["NET_ADMIN"]
          volumeMounts:
            - name: f5gc-upf-config
              mountPath: /free5gc/config
            - name: tun-devdir
              mountPath: /dev/net/tun
          ports:
            - containerPort: 2152
              name: if-n3
              protocol: UDP
            - containerPort: 8805
              name: if-n4
              protocol: UDP
        - name: tcpdump
          image: mobilecore/tcpdump:latest
          imagePullPolicy: IfNotPresent
          command:
            - /bin/sleep
            - infinity
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      serviceAccountName: f5gc-upf-sa
      terminationGracePeriodSeconds: 30
      volumes:
        - name: f5gc-upf-config
          configMap:
            name: f5gc-upf-config
        - name: tun-devdir
          hostPath:
            path: /dev/net/tun
