apiVersion: apps/v1
kind: Deployment
metadata:
  name: open5gs-mme
  labels:
    app: open5gs-mme
spec:
  replicas: 1
  selector:
    matchLabels:
      app: open5gs-mme
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: open5gs-mme
      annotations:
        k8s.v1.cni.cncf.io/networks: open5gs-s1mme-s6a, open5gs-mme-s11
    spec:
      securityContext:
        runAsUser: 0
        runAsGroup: 0
      containers:
        - name: open5gs-mme
          image: registry.gitlab.com/infinitydon/registry/open5gs-aio:v1.2.0
          imagePullPolicy: IfNotPresent
          command: ["open5gs-mmed", "-c", "/open5gs/config-map/mme.yaml"]
          securityContext:
            privileged: false
          volumeMounts:
            - name: open5gs-mme-config
              mountPath: /open5gs/config-map/mme.yaml
              subPath: "mme.yaml"
            - name: open5gs-mme-diameter
              mountPath: /open5gs/config-map/diameter-mme.conf
              subPath: "diameter-mme.conf"
          ports:
            - name: if-s1-mme
              containerPort: 36412
              protocol: SCTP
            - name: if-s6a
              containerPort: 3868
              protocol: SCTP
            - name: if-s11
              containerPort: 2123
              protocol: UDP
        - name: tcpdump
          image: mobilecore/tcpdump:latest
          imagePullPolicy: IfNotPresent
          command:
            - /bin/sleep
            - infinity
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      serviceAccountName: open5gs-mme-sa
      terminationGracePeriodSeconds: 30
      volumes:
        - name: open5gs-mme-config
          configMap:
            name: open5gs-mme-config
        - name: open5gs-mme-diameter
          configMap:
            name: open5gs-mme-diameter
