apiVersion: v1
kind: ConfigMap
metadata:
  name: free5gc-webui-config
  namespace: free5gc
  labels:
    epc-mode: webui
data:
  webuicfg.conf: |
    info:
      version: 1.0.0
      description: WebUI initial local configuration
    
    configuration:
      mongodb:
        name: free5gc
        url: mongodb://localhost:27017