apiVersion: v1
kind: ConfigMap
metadata:
  name: free5gc-udr-config
  namespace: free5gc
  labels:
    epc-mode: udr
data:
  udrcfg.conf: |
    info:
      version: 1.0.0
      description: UDR initial local configuration
    
    configuration:
      sbi:
        scheme: http
        registerIPv4: 10.244.1.8 # IP used to register to NRF
        bindingIPv4: 10.244.1.8  # IP used to bind the service
        port: 29504
      mongodb:
        name: free5gc
        url: mongodb://localhost:27017
      nrfUri: http://10.244.1.7:29510