apiVersion: v1
kind: Service
metadata:
  labels:
    app: f5gc-ue
  name: f5gc-ue
spec:
  type: ClusterIP
  ports:
  - name: f5gc-ue-n1n2
    port: 38412
    protocol: SCTP
    targetPort: 38412
  - name: f5gc-ue-n3
    port: 2152
    protocol: UDP
    targetPort: 2152
  selector:
    app: f5gc-ue
