apiVersion: v1
kind: Service
metadata:
  labels:
    app: dbg-rockmongo
  name: dbg-rockmongo
  namespace: f5gc
spec:
  ports:
  - name: dbg-rockmongo
    port: 8050
    protocol: TCP
    targetPort: 8050
  selector:
    app: dbg-rockmongo
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dbg-rockmongo
  namespace: f5gc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dbg-rockmongo
  template:
    metadata:
      labels:
        app: dbg-rockmongo
    spec:
      containers:
      - env:
        - name: MONGO_HOSTS
          value: f5gc-mongodb:27017
        - name: ROCKMONGO_PORT
          value: "8050"
        - name: MONGO_HIDE_SYSTEM_COLLECTIONS
          value: "false"
        - name: MONGO_AUTH
          value: "false"
        - name: ROCKMONGO_USER
          value: testadmin
        - name: ROCKMONGO_PASSWORD
          value: testadmin
        image: tadaweb/rockmongo
        name: dbg-rockmongo
        ports:
        - containerPort: 8050
          name: http
