apiVersion: v1
kind: ServiceAccount
metadata:
  name: f5gc-smf-sa
  namespace: f5gc
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: f5gc-smf-rbac
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: f5gc-smf-sa
  namespace: f5gc
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: f5gc-smf-config
  namespace: f5gc
data:
  smfcfg.conf: |
    info:
      version: 1.0.0
      description: AMF initial local configuration
    
    configuration:
      smfName: SMF
      sbi:
        scheme: http
        registerIPv4: f5gc-smf
        bindingIPv4: 0.0.0.0 
        port: 29502
        tls:
          key: free5gc/support/TLS/smf.key
          pem: free5gc/support/TLS/smf.pem
      serviceNameList:
        - nsmf-pdusession
        - nsmf-event-exposure
      snssai_info:
        - sNssai:
            sst: 1
            sd: 010203
          dnnSmfInfoList:
            - dnn: internet
        # - sNssai:
        #     sst: 1
        #     sd: 112233
        #   dnnSmfInfoList:
        #     - dnn: internet
      pfcp:
        addr: 172.16.30.20
      userplane_information:
        up_nodes:
          gNB1:
            type: AN
            an_ip: 192.168.10.10
          UPF1:
            type: UPF
            node_id: 172.16.30.30
        links:
          - A: gNB1
            B: UPF1
      dnn:
        internet:
          dns:
            ipv4: 8.8.8.8
            ipv6: 2001:4860:4860::8888
        internet2:
          dns:
            ipv4: 8.8.4.4
            ipv6: 2001:4860:4860::8844
      ue_subnet: 172.16.1.0/24
      nrfUri: http://f5gc-nrf:29510
  uerouting.yaml: |
    info:
      version: 1.0.0
      description: Routing information for UE

    ueRoutingInfo:
      - SUPI: imsi-2089300007487
        AN: 10.200.200.101
        PathList:
          - DestinationIP: 60.60.0.101
            DestinationPort: 8888
            UPF: !!seq
              - BranchingUPF
              - AnchorUPF1

          - DestinationIP: 60.60.0.103
            DestinationPort: 9999
            UPF: !!seq
              - BranchingUPF
              - AnchorUPF2

      - SUPI: imsi-2089300007486
        AN: 10.200.200.102
        PathList:
          - DestinationIP: 10.0.0.10
            DestinationPort: 8888
            UPF: !!seq
              - BranchingUPF
              - AnchorUPF1

          - DestinationIP: 10.0.0.11
            DestinationPort: 9999
            UPF: !!seq
              - BranchingUPF
              - AnchorUPF2

    # routeProfile:
    #   MEC1:
    #     forwardingPolicyID: 10
    #
    # pfdDataForApp:
    #   - applicationId: edge
    #     pfds:
    #       - pfdID: pfd1
    #         flowDescriptions:
    #           - permit out ip from 60.60.0.1 8080 to any
  free5GC.conf: |
    db_uri: mongodb://f5gc-mongodb:27017/free5GC
    #all logging levels
    #panic
    #fatal
    #error
    #warn
    #info
    #debug
    #trace
    logger:
    # network function
      AMF:
        debugLevel: info
        ReportCaller: true
      SMF:
        debugLevel: debug
        ReportCaller: true
      UDR:
        debugLevel: info
        ReportCaller: true
      UDM:
        debugLevel: info
        ReportCaller: true
      NRF:
        debugLevel: info
        ReportCaller: true
      PCF:
        debugLevel: info
        ReportCaller: true
      AUSF:
        debugLevel: info
        ReportCaller: true
      N3IWF:
        debugLevel: info
        ReportCaller: true
    # library
      NAS:
        debugLevel: info
        ReportCaller: true
      FSM:
        debugLevel: info
        ReportCaller: true
      NGAP:
        debugLevel: info
        ReportCaller: true
      NamfComm:
        debugLevel: info
        ReportCaller: true
      NamfEventExposure:
        debugLevel: info
        ReportCaller: true
      NsmfPDUSession:
        debugLevel: info
        ReportCaller: true
      NudrDataRepository:
        debugLevel: info
        ReportCaller: true
      OpenApi:
        debugLevel: debug
        ReportCaller: true
      Aper:
        debugLevel: info
        ReportCaller: true
      CommonConsumerTest:
        debugLevel: info
        ReportCaller: true
    # webui
      WEBUI:
        debugLevel: info
        ReportCaller: true
---
apiVersion: v1
kind: Secret
metadata:
  name: f5gc-smf-tls-secret
  namespace: f5gc
type: Opaque
data:
  smf.key: |
    LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFb3dJQkFBS0NBUUVBM1NVM3
    lWcnA1SWc5YVJGaDNPV3R2eWR4SkMvWnpBOHppanJTUmxkckNNRWhDUHNYCkM2aHR4UGlv
    bHlZZlg5NW9vRzNsVWhVOEtIdW5RNlJrQnFZdHhLSHJrL3VTZU42aURPeHYyZDRjcDdNdF
    RsSG4KdWM5U216T09pVTl0Nk1IMlVpWEMwdDdoR0JRc2hFNmxTWExFU0ErWkdXYmJyYWJh
    Mmo1Y295SWFSM0tKdHl1YwozZDBYOEFUN0pGVW5NL2hQTEJkR0o1ZzFlazcvMm1OMGpYV3
    k0aUNYSWVENXNQRCthSTBqSTV3YXE1WE1mbDJLCmJPVTlYNjl6MmZMbndDY3d4V1hrcDNo
    WkR0eFozYmdXRFplK2w3TXgyNVFVd1A3R0krTUhXWTdDTVJFVVk0Q0EKTXVXY0xudUN4aH
    VqYkUzQ0RBNzJjWjRCNS9OV3JIZG80clFMNFFJREFRQUJBb0lCQVFDK1J0aXlPclJHdTJi
    RApjWDVYdDVPQWh1cFZyWXBqaHF6ZEFmR05Mb2hjMXZlYXA1alRvZzhZeks4YXBtV1djbU
    pwcjBVQ0ZGMVhvOVZ1CllSTGptYmFGbXFCOUNwZWp3a09DaFNsVU4wVkdrZWVvbk5hYVRL
    V1IvcEZrMmVBQ3hta3ZrMmdIVWxneEJLS3QKRUpJdEdUK0RsVkF3eUF5NlpIZW9Fc0pZWn
    U1Zmk3Y2lpSkhMQXVLSTRXL2EwU1pMRmVsY3czaU9oaVZ5UXJNRQoxQzBCZ1pXMG9VQ2Nz
    VHk1c2EyN0ZzL09TUXZDRnl5RHVUTE1LNWxQZ2trVXpobmhuQTN6YkJiOWhqS1RkQ3lHCn
    NnM0k5RENSd1dHMUMvQ0wxL1cycjdzNkFoSXYyNFluMUc3S0czS21RQ08zZ21vbXMvQnpP
    Uis0THJrTjNudmEKV1d6VkpsRHhBb0dCQVBMcUJFeGp4eWcveDBzZFpGOGRERlFVOG9BM3
    g4cEx2eGtxekpXYVZLZjhkM1lMNUdJNApBV3lNdGl6MGtXU1hIZmsxdEVQb3NHM212Rndp
    b3VoMUsxa0U5cEhvNFdycWZVdDlSQ2lFWkV6bDlSOXgyT3BsCkJPejJjME9sOFZwanJSQk
    JmM1BWNmtYbUdFRTlJQTFmMG9UdmE4bEJJck9iNWdRY01SYlQvU3VWQW9HQkFPa08KL2hB
    OEdwK2VrbU83cWlHY1VRaEI3L3Ria3dvYWYrbzJBOEdsYXNQUnovd3ViUFRvZ3N2cWU2RH
    FRUW81NnY2Lwp6WTBtcEZBRHRXeXlxYTRBdmtHd0cvVzRKRjdCZFErazNLSS9EMkdoNWdI
    YnpuMDFjWkFTdlhBWW5NMEFXaS90CmRPcks5SDhjZytFN1lKS3lvY2xId2wybjUvUVhYVG
    lxQytDdlJxd2RBb0dBQkRFcnI5SE0veEhTczZZbk5Fa0IKREhac0ZQQmhmMGs5WEFiVUR3
    VGh6eUJaUTIxREhMclFzM25lTHZwdGcrbmp0NGhJdXg5SjVDdW1Ob1RXZ09KOAp4QVdFNT
    lHNENpdFB6RHkyTDJqUmZrNDlvN1JJUlF0SFFYdWpVNWlLaUwvTm5ja3psT0V0TU5XZXQ0
    bUJneG1UClBYNFFReUhmb20vZlVWVFhPQWlpaHQwQ2dZQlFtWS9CKzVkVmhwaW9Cem5pWD
    lZaVhmTnA0WlNybE5pU0hsWVUKUFduOENPNitEeXc5VXNBUlY2bWp6Ly9vVW5sejJzOXl0
    bDl6RUtWSXowMGhVVDU3SnpXME9CZlQ4V0hUcERkdApvUk5udDM3OU81QmcrditvVE9MWk
    Jwb0x4OGhvOU4xUGFocyticFVwYXNpT1Uxcmlhbi9NdGduZy84ZU1sanAvClhQNjYvUUtC
    Z0FzYWlHcXAxalRwb2E2UXRHRGo4TkgwR3NlNjFBNElMdUM3dHRpUkVKWkRvSnlKZWxjRj
    VJSjUKeUxKa3V5K1I1a3pYMFY3ckN3WWM1QXhFM1llVHRlVG1ybXNzK3VGSm84NUJxTjRk
    TEZMRlpzbUVyYVhwd0xiTAovR09zUURGM1BlT2pKUEhyYWZ2aThKWWNrWnNqVWN3TjdZbj
    NIYnNRY3ZnaTU5RUhMbFRkCi0tLS0tRU5EIFJTQSBQUklWQVRFIEtFWS0tLS0tCg==
  smf.pem: |
    LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURhekNDQWxPZ0F3SUJBZ0lVZWpXM0
    l3K0pxYzZVaW1Eak5MNUEyaWlUTExJd0RRWUpLb1pJaHZjTkFRRUwKQlFBd1JURUxNQWtH
    QTFVRUJoTUNRVlV4RXpBUkJnTlZCQWdNQ2xOdmJXVXRVM1JoZEdVeElUQWZCZ05WQkFvTQ
    pHRWx1ZEdWeWJtVjBJRmRwWkdkcGRITWdVSFI1SUV4MFpEQWVGdzB4T1RBM01URXdOekkx
    TVRoYUZ3MHlPVEEzCk1EZ3dOekkxTVRoYU1FVXhDekFKQmdOVkJBWVRBa0ZWTVJNd0VRWU
    RWUVFJREFwVGIyMWxMVk4wWVhSbE1TRXcKSHdZRFZRUUtEQmhKYm5SbGNtNWxkQ0JYYVdS
    bmFYUnpJRkIwZVNCTWRHUXdnZ0VpTUEwR0NTcUdTSWIzRFFFQgpBUVVBQTRJQkR3QXdnZ0
    VLQW9JQkFRRGRKVGZKV3Vua2lEMXBFV0hjNWEyL0ozRWtMOW5NRHpPS090SkdWMnNJCndT
    RUkreGNMcUczRStLaVhKaDlmM21pZ2JlVlNGVHdvZTZkRHBHUUdwaTNFb2V1VCs1SjQzcU
    lNN0cvWjNoeW4Kc3kxT1VlZTV6MUtiTTQ2SlQyM293ZlpTSmNMUzN1RVlGQ3lFVHFWSmNz
    UklENWtaWnR1dHB0cmFQbHlqSWhwSApjb20zSzV6ZDNSZndCUHNrVlNjeitFOHNGMFlubU
    RWNlR2L2FZM1NOZGJMaUlKY2g0UG13OFA1b2pTTWpuQnFyCmxjeCtYWXBzNVQxZnIzUFo4
    dWZBSnpERlplU25lRmtPM0ZuZHVCWU5sNzZYc3pIYmxCVEEvc1lqNHdkWmpzSXgKRVJSam
    dJQXk1Wnd1ZTRMR0c2TnNUY0lNRHZaeG5nSG44MWFzZDJqaXRBdmhBZ01CQUFHalV6QlJN
    QjBHQTFVZApEZ1FXQkJRWGVmVEdCS0haeldWcFNJU0wvTzNVS09qdXVEQWZCZ05WSFNNRU
    dEQVdnQlFYZWZUR0JLSFp6V1ZwClNJU0wvTzNVS09qdXVEQVBCZ05WSFJNQkFmOEVCVEFE
    QVFIL01BMEdDU3FHU0liM0RRRUJDd1VBQTRJQkFRQUgKZnBvbkJ4dE1vd2VWUDI0dHBZL2
    dJWUlRRE1tcjZ6R3NsV0pqQlRTNGF6Qkw1L3JkazFwWms2b25SZlFEN3pBWgpCQnorUkJT
    bk5ReDlOMjNaaU5lKzkzdzlMN2dGNzRFT3hSTDlzQ2EyaTFJRGJVdmVyeFRtdjBSbVY0WH
    VHdGJJCnJhajAyRGxVTEkrUkdzS1VmcVNCTmNaVUFZeWpFS0laamE1MzFlcStkUnlQN3Fn
    eXZjd0s0NGYxQnNuTFN5U0gKajk1OHgxellRRnF2YjRxYXFDMDViTlUrQ1Z1d2FTMGUrd2
    JQMWhDWG5jb2czWUtBa0hZSnFaWlRqbjE1YjhPcAp2MXJwcEVGZGpLN3BDb1JiNnZQMzlF
    Zm81dVJDakd3ZFRaWWdwaFg0YmVnbk4vbXVENjlvOHNFc3c2MEZ1emd0Ck9XN0NIdHdSMl
    pBVVBKWVVLMDRGCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: f5gc-smf
  name: f5gc-smf
  namespace: f5gc
spec:
  ports:
  - name: f5gc-smf-sbi
    port: 29502
    protocol: TCP
    targetPort: 29502
  - name: f5gc-smf-n4
    port: 8805
    protocol: UDP
    targetPort: 8805
  selector:
    app: f5gc-smf
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: f5gc-smf
  namespace: f5gc
  labels:
    app: f5gc-smf
    sliceidx: 6d3d79da-f781-4cd9-813a-dbdad01e01c0
  annotations:
    free5gc.org/nsi-ids: '[ 
      { "id": "4e6db941-47d6-4fce-9c71-f7eb35a75d03" }, 
    ]'
    free5gc.org/nssi-id: 27394d25-dbf5-428e-8fc3-f5b2add67115
    free5gc.org/supported-snssais: '[ 
      { "st": 1, 
        "ssd": "010203",
      },
      { "st": 1,
        "ssd": "112233",
      },
    ]'
spec:
  replicas: 1
  selector:
    matchLabels:
      app: f5gc-smf
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        k8s.v1.cni.cncf.io/networks: f5gc-smf-n4
      labels:
        app: f5gc-smf
    spec:
      containers:
      - name: f5gc-smf
        image: monandkey/free5gc-smf:3.0.4
        imagePullPolicy: IfNotPresent
        command: [./smf]
        ports:
        - containerPort: 29502
          name: if-sbi
          protocol: TCP
        - containerPort: 8805
          name: if-n4
          protocol: UDP
        securityContext:
          privileged: false
        volumeMounts:
        - mountPath: /free5gc/config
          name: f5gc-smf-config
        - mountPath: /free5gc/support/TLS
          name: f5gc-smf-cert
      - name: tcpdump
        image: corfr/tcpdump
        imagePullPolicy: IfNotPresent
        command:
        - /bin/sleep
        - infinity
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        runAsGroup: 0
        runAsUser: 0
      serviceAccountName: f5gc-smf-sa
      terminationGracePeriodSeconds: 30
      volumes:
      - name: f5gc-smf-cert
        secret:
          secretName: f5gc-smf-tls-secret
      - configMap:
          name: f5gc-smf-config
        name: f5gc-smf-config
---
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition 
metadata:
  name: f5gc-smf-n4
spec:
  config: '{ 
      "cniVersion": "0.3.1",
      "type": "macvlan",
      "master": "eth1",
      "mode": "bridge",
      "ipam": {
        "type": "static",
        "addresses": [
                {
                        "address": "172.16.30.20/24",
                        "gateway": "172.16.30.1"
                }
        ]
      }
    }'
