apiVersion: v1
kind: ServiceAccount
metadata:
  name: f5gc-upf-sa
  namespace: f5gc
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: f5gc-upf-rbac
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: f5gc-upf-sa
  namespace: f5gc
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: f5gc-upf-config
  namespace: f5gc
data:
  upfcfg.yaml: |
    info:
      version: 1.0.0
      description: UPF configuration

    configuration:
      # debugLevel: panic|fatal|error|warn|info|debug|trace
      debugLevel: info
      # ReportCaller: true|false
      ReportCaller: false

      pfcp:
        - addr: 172.16.30.30

      gtpu:
        - addr: 192.168.10.20
        # [optional] gtpu.name
        # - name: upf.5gc.nctu.me
        # [optional] gtpu.ifname
        # - ifname: gtpif

      dnn_list:
        - dnn: internet
          cidr: 172.16.1.0/24
          # [optional] apn_list[*].natifname
          # natifname: eth0
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: f5gc-upf
  name: f5gc-upf
  namespace: f5gc
spec:
  ports:
  - name: f5gc-upf-n3
    port: 2152
    protocol: UDP
    targetPort: 2152
  - name: f5gc-upf-n4
    port: 8805
    protocol: UDP
    targetPort: 8805
  selector:
    app: f5gc-upf
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: f5gc-upf
  namespace: f5gc
  labels:
    app: f5gc-upf
    sliceidx: 6d3d79da-f781-4cd9-813a-dbdad01e01c0
  annotations:
    free5gc.org/nsi-ids: '[ 
      { "id": "4e6db941-47d6-4fce-9c71-f7eb35a75d03" },
    ]'
    free5gc.org/nssi-id: 27394d25-dbf5-428e-8fc3-f5b2add67115
spec:
  replicas: 1
  selector:
    matchLabels:
      app: f5gc-upf
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        k8s.v1.cni.cncf.io/networks: f5gc-upf-n3, f5gc-upf-n4, f5gc-upf-n6
      labels:
        app: f5gc-upf
    spec:
      containers:
      - name: f5gc-upf
        image: monandkey/free5gc-upf:3.0.4
        imagePullPolicy: IfNotPresent
        command: [./upf]
        ports:
        - containerPort: 2152
          name: if-n3
          protocol: UDP
        - containerPort: 8805
          name: if-n4
          protocol: UDP
        securityContext:
          capabilities:
            add:
            - NET_ADMIN
            - NET_RAW
            - NET_BIND_SERVICE
            - SYS_TIME
          privileged: false
        volumeMounts:
        - mountPath: /free5gc/config
          name: f5gc-upf-config
        - mountPath: /dev/net/tun
          name: tun-devdir
      - name: tcpdump
        image: corfr/tcpdump
        command:
        - /bin/sleep
        - infinity
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        runAsGroup: 0
        runAsUser: 0
      serviceAccountName: f5gc-upf-sa
      terminationGracePeriodSeconds: 30
      volumes:
      - configMap:
          name: f5gc-upf-config
        name: f5gc-upf-config
      - hostPath:
          path: /dev/net/tun
        name: tun-devdir
---
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition 
metadata:
  name: f5gc-upf-n3
spec:
  config: '{ 
      "cniVersion": "0.3.1",
      "type": "macvlan",
      "master": "eno2",
      "mode": "bridge",
      "ipam": {
        "type": "static",
        "addresses": [
                {
                        "address": "192.168.10.20/24",
                        "gateway": "192.168.10.1"
                }
        ]
      }
    }'

---
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: f5gc-upf-n4
spec:
  config: '{
      "cniVersion": "0.3.1",
      "type": "macvlan",
      "master": "eno2",
      "mode": "bridge",
      "ipam": {
        "type": "static",
        "addresses": [
                {
                        "address": "172.16.30.30/24",
                        "gateway": "172.16.30.1"
                }
        ]
      }
    }'
---
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: f5gc-upf-n6
spec:
  config: '{
      "cniVersion": "0.3.1",
      "type": "macvlan",
      "master": "eno2",
      "mode": "bridge",
      "ipam": {
        "type": "static",
        "addresses": [
                {
                        "address": "172.16.31.30/24",
                        "gateway": "172.16.31.1"
                }
        ]
      }
    }'
