apiVersion: v1
kind: ServiceAccount
metadata:
  name: f5gc-pcf-sa
  namespace: f5gc
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: f5gc-pcf-rbac
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: f5gc-pcf-sa
  namespace: f5gc
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: f5gc-pcf-config
  namespace: f5gc
data:
  pcfcfg.conf: |
    info:
      version: 1.0.0
      description: PCF initial local configuration

    configuration:
      pcfName: PCF
      sbi:
        scheme: http
        registerIPv4: f5gc-pcf
        bindingIPv4: 0.0.0.0
        port: 29507
      timeFormat: 2019-01-02 15:04:05
      defaultBdtRefId: BdtPolicyId-
      nrfUri: http://f5gc-nrf:29510
      serviceList:
        - serviceName: npcf-am-policy-control
        - serviceName: npcf-smpolicycontrol
          suppFeat: 3fff
        - serviceName: npcf-bdtpolicycontrol
        - serviceName: npcf-policyauthorization
          suppFeat: 3
        - serviceName: npcf-eventexposure
        - serviceName: npcf-ue-policy-control
  free5GC.conf: |
    db_uri: mongodb://f5gc-mongodb:27017/free5gc

    #all logging levels
    #panic
    #fatal
    #error
    #warn
    #debug
    #debug
    #trace
    logger:
    # network function
      AMF:
        debugLevel: debug
        ReportCaller: true
      SMF:
        debugLevel: debug
        ReportCaller: true
      UDR:
        debugLevel: debug
        ReportCaller: true
      UDM:
        debugLevel: debug
        ReportCaller: true
      NRF:
        debugLevel: debug
        ReportCaller: true
      PCF:
        debugLevel: debug
        ReportCaller: true
      AUSF:
        debugLevel: debug
        ReportCaller: true
      N3IWF:
        debugLevel: debug
        ReportCaller: true
    # library
      NAS:
        debugLevel: debug
        ReportCaller: true
      FSM:
        debugLevel: debug
        ReportCaller: true
      NGAP:
        debugLevel: debug
        ReportCaller: true
      NamfComm:
        debugLevel: debug
        ReportCaller: true
      NamfEventExposure:
        debugLevel: debug
        ReportCaller: true
      NsmfPDUSession:
        debugLevel: debug
        ReportCaller: true
      NudrDataRepository:
        debugLevel: debug
        ReportCaller: true
      OpenApi:
        debugLevel: debug
        ReportCaller: true
      Aper:
        debugLevel: debug
        ReportCaller: true
      CommonConsumerTest:
        debugLevel: debug
        ReportCaller: true
    # webui
      WEBUI:
        debugLevel: debug
        ReportCaller: true
---
apiVersion: v1
kind: Secret
metadata:
  name: f5gc-pcf-tls-secret
  namespace: f5gc
type: Opaque
data:
  pcf.key: |
    LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFcEFJQkFBS0NBUUVBdnJBRD
    k0M0VYRkcxc1dRWXY0SHpNV0FzWmR2eXBFK3RhUkdhRkI0SW9xUHBQS0xqCmdKTjZ3c0hF
    MTZlaGlzaXhNWEx3VE5tdWFpVDZCQVdETEtTdUxUQUpFTkIvM3dYODlHYTNLR0VvOUJLT1
    Z5MGoKbFUzUFpEZkdTNkNyYzFJMnh5VDVjd3RaZTg1aDk0MVh0UENrdVN5SU8yWkR6MnVU
    NWNPai9IbTFnTGVacUVYQworNmZseTdLODdEVXJvc09YQVZ4UnRNaHlZRU5lVEdRUFpWOV
    djd3FxaTNmKzAxa1ZoRVNtVDNoVHc0dTVmL25uCitJc3g5OXVad3NIQmxrbWlVQzlwcmdl
    ZjlqZE4xK0d3ZlVLcHRURFBQektOTW4vYUc3Z2xLczlWbkkzcGNnaGEKV29VRU5Na2hTT3
    dJdmZlUFBmMVBGMzV5RUs1ZmRtMkhmeENOVFFJREFRQUJBb0lCQVFDaWVSYm9Oc0s0Wm1h
    SgpYdUEzVEdJS0VBZkVRa1BiL0lla25ucko2VTB5UnJiVUUzWUVkNlNCak5oTFoya2M5eU
    1ESHd2Z2J4bE5GM1J2Ck9NTXJwcVZCbTB3ZUo0ak1YaTNKa0RzL0RJbjRiRmNic0RwQlhL
    cjRtUTA4SXdueW1IcFQ5QTBYR1BTRnFMT1EKV2I0QlRZa012Z1RWbDZ6dmJwbjFpMXlPSX
    FXanBWTW1tb2ZBN0VOTHRCSnhxK3ZNSWhrczNQZDh4ancyYlVlTApTYzZQRGM4bWY1U3Zz
    ankrdklYNHd6ZGErTkQ5NVF5RnlUVjlPK0xpaWEzSlUrVnZhb1RVVHRMcjhPd1dtVXc5Cl
    Y3ZDNYeUNkZHcyRmFzbUI5T2ZVSERzdmFnczJEb0NocDNTK3poMFYzWURRbENKdjl2MTEx
    TDdyTUpGVUE4VW8KS2ZWb2huT0JBb0dCQU9pSVZ4dGNxRTV4eHJXakpsSGMxbGpCWTZlZ3
    FSTk5nUkJXc3RjVzdXY3R4R1FBQVlDeQpESXBZY2dSZk5LZ1RoY2VyTEphMGh5K1RIQkZO
    amg5YzM1dkxmTC9tT1hFSEU0dHcyTXNaR3I4SS9wOWU3YzdpCm03YVI0M21VWE1vWW9jYk
    Q5aHRaL3hzMHpSK256dXJUNlVFVkhUN2M1cWIvaWZVNFVZeTkyQVp2QW9HQkFOSHUKazZI
    R0U2dWlJKzUzUnd6YzVVdjR0ODBGNXhHZzMxeUVnTlhtY3EwcENpWU5qdTkwZ3ZNV1hKdW
    pkcXRLUVhXRgp4bkdvYmNoenpSb01jbHNPcG1BRGdleU9JZjBGSHVlMVcyVS9xMmFuWkpw
    bVpGejlBcHZMaVRHZlgxbnR1Yll3CjVScmlTZTA4YzUwU2E2bmFHRjNNWGlKcnF3Y01XZG
    pOcWdBK3JDWURBb0dBUGZiVy8zdVpmZzNqbmROMENxeUcKa2ZBMjFoeUI4WnJkb2JUNHcw
    aGd5dlh2TjVhb3o5cWliTnRVeHNWNENySHBIR1FJNWNBRnBpL1ZjdWJ2MEh1MwpPcFRuRV
    Z3UVFvWllOdmhEVFJ2TGZNeXd6VmRHbDdMYk83TjBvcGxlZ0p3L3YrL0lUVkdXSVhIWWwy
    N29QTHRyCmxPUkRmdFR1d2VHbXFhbndVVWpsb0JFQ2dZQmpJeng2cUJTLzk4anFJMC9kUm
    kvT2liMGF5QS9QNWwyMHppb2QKV1QrTWdKWDNWRzNNclFQdUVnQlh5NEVOOFBvcXFxc0ZI
    NW9Ba0pjcUZ2aW1BYXdXS1hIZ3FWcHBwMUpwNzk0aQpXVWZ6S1ZlOEJtQ2MvU3FQTWpZdX
    hlbDhpV1FySXJuKzBTQkNOVXNQd1JRdzJQcXF5UWtuVGhzdEwrcjZGRjJVCjBnUHZ5d0tC
    Z1FET0hnY3pISStHOHBnaXZ6QzJXNk9VdkltbTdERUZLWncyWlJORlNxcTAva3NXZlVuWU
    lVYWYKS3lOaEtPQ21DcVlTWnI2aXZYNDdkTzlHMng4T001dTk1cGFZOHlzT0IrbWx4L3ly
    WEtJOEI0Wk1heDN4YVZNcQpRRHdpV2NzR042VlV2eVdJVHlERHNvVWdXSzdzUHNWY29KZ3
    ZWS2R1ei9WUmtQWmsyWU5HeUE9PQotLS0tLUVORCBSU0EgUFJJVkFURSBLRVktLS0tLQo=
  pcf.pem: |
    LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURTRENDQWpBQ0NRRFFMRXJWWS9lRT
    hEQU5CZ2txaGtpRzl3MEJBUXNGQURCbU1Rc3dDUVlEVlFRR0V3SlUKVnpFUE1BMEdBMVVF
    Q0F3R1ZHRnBkMkZ1TVE4d0RRWURWUVFIREFaVVlXbHdaV2t4RFRBTEJnTlZCQW9NQkU1VQ
    pRMVV4RERBS0JnTlZCQXNNQTBsUFZERVlNQllHQTFVRUF3d1BkM2QzTG01MFkzVXVaV1Ix
    TG5SM01CNFhEVEU1Ck1EY3lNekF6TWpjd00xb1hEVEk1TURjeU1EQXpNamN3TTFvd1pqRU
    xNQWtHQTFVRUJoTUNWRmN4RHpBTkJnTlYKQkFnTUJsUmhhWGRoYmpFUE1BMEdBMVVFQnd3
    R1ZHRnBjR1ZwTVEwd0N3WURWUVFLREFST1ZFTlZNUXd3Q2dZRApWUVFMREFOSlQxUXhHRE
    FXQmdOVkJBTU1EM2QzZHk1dWRHTjFMbVZrZFM1MGR6Q0NBU0l3RFFZSktvWklodmNOCkFR
    RUJCUUFEZ2dFUEFEQ0NBUW9DZ2dFQkFMNndBL2VOeEZ4UnRiRmtHTCtCOHpGZ0xHWGI4cV
    JQcldrUm1oUWUKQ0tLajZUeWk0NENUZXNMQnhOZW5vWXJJc1RGeThFelpybW9rK2dRRmd5
    eWtyaTB3Q1JEUWY5OEYvUFJtdHloaApLUFFTamxjdEk1Vk56MlEzeGt1Z3EzTlNOc2NrK1
    hNTFdYdk9ZZmVOVjdUd3BMa3NpRHRtUTg5cmsrWERvL3g1CnRZQzNtYWhGd3Z1bjVjdXl2
    T3cxSzZMRGx3RmNVYlRJY21CRFhreGtEMlZmVm5NS3FvdDMvdE5aRllSRXBrOTQKVThPTH
    VYLzU1L2lMTWZmYm1jTEJ3WlpKb2xBdmFhNEhuL1kzVGRmaHNIMUNxYlV3eno4eWpUSi8y
    aHU0SlNyUApWWnlONlhJSVdscUZCRFRKSVVqc0NMMzNqejM5VHhkK2NoQ3VYM1p0aDM4UW
    pVMENBd0VBQVRBTkJna3Foa2lHCjl3MEJBUXNGQUFPQ0FRRUFCdE81UmUzZWtrWEdnQkdE
    QkJ4QnpmSVY5SDE5czR4aTNzSWhhdjhkMjB1YVQwbEsKcllsWUlGSDRVN3lpMmVJczYwT1
    dEYTVrQVRyT3RUZUUzUTloUTR6Wk1xOHhsZXJ6OHcvbXVSUy8xQWNqSTZ5MApNWFFJaXYr
    UlZOZVdyV1N3YU9YUERqT1hJUDFRakc4V0VkZEpnNERNdTRjb3BHU21MbHYrRVRZUnVFNk
    9rbGdVCllVZ3UrRm8rNzNVQUw4TE1RRndYTnBmdnRrdndXTEVaaFB2a2JNZ25UWS8xZGEr
    QklYMG5KcWtLeHkyRTV4WWYKZ1JNUHNkNkRkY1ExeUhjL2I5MEcwWDNWUlNhVWdXOTdTUG
    9FbitMRnVRTUowYUlON281TytHVzc0eVVmeXhNbwpWVkY1OUR6NkZVQWsrUHVwWVd2anNo
    MnRMOTJSL3RkeWtTbERWdz09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: f5gc-pcf
  name: f5gc-pcf
  namespace: f5gc
spec:
  ports:
  - name: f5gc-pcf
    port: 29507
    protocol: TCP
    targetPort: 29507
  selector:
    app: f5gc-pcf
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: f5gc-pcf
  namespace: f5gc
  labels:
    app: f5gc-pcf
  annotations:
    free5gc.org/nsi-ids: '[ 
      { "id": "4e6db941-47d6-4fce-9c71-f7eb35a75d03" },
    ]'
    free5gc.org/nssi-id: 27394d25-dbf5-428e-8fc3-f5b2add67115
spec:
  replicas: 1
  selector:
    matchLabels:
      app: f5gc-pcf
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: f5gc-pcf
    spec:
      containers:
      - name: f5gc-pcf
        image: monandkey/free5gc-pcf:3.0.4
        imagePullPolicy: IfNotPresent
        command: [./pcf]
        ports:
        - containerPort: 29507
          name: f5gc-pcf
          protocol: TCP
        securityContext:
          privileged: false
        volumeMounts:
        - mountPath: /free5gc/config
          name: f5gc-pcf-config
        - mountPath: /free5gc/support/TLS
          name: f5gc-pcf-cert
      - name: tcpdump
        image: corfr/tcpdump
        command:
        - /bin/sleep
        - infinity
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        runAsGroup: 0
        runAsUser: 0
      serviceAccountName: f5gc-pcf-sa
      terminationGracePeriodSeconds: 30
      volumes:
      - name: f5gc-pcf-cert
        secret:
          secretName: f5gc-pcf-tls-secret
      - configMap:
          name: f5gc-pcf-config
        name: f5gc-pcf-config
