apiVersion: v1
kind: ServiceAccount
metadata:
  name: f5gc-n6dummy-sa
  namespace: f5gc
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: f5gc-n6dummy-rbac
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: f5gc-n6dummy-sa
  namespace: f5gc
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: f5gc-n6dummy
  name: f5gc-n6dummy
  namespace: f5gc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: f5gc-n6dummy
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        k8s.v1.cni.cncf.io/networks: f5gc-n6dummy-n6
      labels:
        app: f5gc-n6dummy
    spec:
      containers:
      - name: f5gc-n6dummy
        image: docker.io/centos/tools:latest
        imagePullPolicy: IfNotPresent
        securityContext:
          privileged: true
        command:
        - /sbin/init
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        runAsGroup: 0
        runAsUser: 0
      serviceAccountName: f5gc-n6dummy-sa
      terminationGracePeriodSeconds: 30
---
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: f5gc-n6dummy-n6
spec:
  config: '{
      "cniVersion": "0.3.1",
      "type": "macvlan",
      "master": "eno2",
      "mode": "bridge",
      "ipam": {
        "type": "static",
        "addresses": [
                {
                        "address": "172.16.31.100/24",
                        "gateway": "172.16.31.1"
                }
        ]
      }
    }'
