apiVersion: v1
kind: ServiceAccount
metadata:
  name: f5gc-gnbsim-sa
  namespace: f5gc
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: f5gc-gnbsim-rbac
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: f5gc-gnbsim-sa
  namespace: f5gc
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: f5gc-gnbsim-config
  namespace: f5gc
data:
  example.json: |
    {
            "GlobalGNBID": {
                    "mcc": 208,
                    "mnc": 93,
                    "gnbid": 1
            },
            "SupportedTAList" : [
                    {
                            "TAC": "0x000001",
                            "BroadcastPLMNList": [
                                    {
                                            "MCC": 208,
                                            "MNC": 93,
                                            "SliceSupportList": [
                                                    {
                                                            "SST": 1,
                                                            "SD": "010203"
                                                    }
                                            ]
                                    }
                            ]
                    }
            ],
            "PagingDRX" : "v32",
            "RANUENGAPID" : 0,
            "UE": {
                    "imeisv": "0000000100000101",
                    "msin": "0000000003",
                    "mcc": 208,
                    "mnc": 93,
                    "RoutingIndicator": 1234,
                    "ProtectionScheme": "null",
                    "AuthParam": {
                            "K": "8baf473f2f8fd09487cccbd7097c6862",
                            "OPc": "8e27b6af0e692e750f32667a3b14605d"
                    },
                    "snssai": {
                            "sst": 1,
                            "sd": "010203"
                    },
                    "dnn": "internet",
                    "url": "http://localhost/"
            },
            "ULInfoNR": {
                    "NRCGI": {
                            "PLMN": {
                                    "mcc": 208,
                                    "mnc": 93
                            },
                            "NRCellID": 1
                    },
                    "TAI": {
                            "PLMN": {
                                    "mcc": 208,
                                    "mnc": 93
                            },
                            "TAC": "0x000001"
                    }
            },
            "GTPuAddr": "192.168.10.10",
            "GTPuIFname": "net2"
    }
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: f5gc-gnbsim
  name: f5gc-gnbsim
  namespace: f5gc
spec:
  ports:
  - name: f5gc-gnbsim-n1n2
    port: 38412
    protocol: SCTP
    targetPort: 38412
  - name: f5gc-gnbsim-n3
    port: 2152
    protocol: UDP
    targetPort: 2152
  selector:
    app: f5gc-gnbsim
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: f5gc-gnbsim
  namespace: f5gc
  labels:
    app: f5gc-gnbsim
  annotations:
    free5gc.org/nsi-ids: '[ 
      { "id": "4e6db941-47d6-4fce-9c71-f7eb35a75d03" },
    ]'
    free5gc.org/nssi-id: 27394d25-dbf5-428e-8fc3-f5b2add67115
    free5gc.org/supported-snssais: '[ 
      { "st": 1,
        "ssd": "010203",
      },
      { "st": 1,
        "ssd": "112233",
      },
    ]'
spec:
  replicas: 1
  selector:
    matchLabels:
      app: f5gc-gnbsim
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        k8s.v1.cni.cncf.io/networks: f5gc-gnbsim-n1n2, f5gc-gnbsim-n3
      labels:
        app: f5gc-gnbsim
    spec:
      containers:
      - name: f5gc-gnbsim
        image: monandkey/gnbsim:0.0.1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 38412
          name: if-n1n2
          protocol: SCTP
        - containerPort: 2152
          name: if-n3
          protocol: UDP
        securityContext:
          capabilities:
            add:
            - NET_ADMIN
            - SYS_TIME
          privileged: true
        tty: true
        volumeMounts:
        - mountPath: /gnbsim/example-sample.json
          name: f5gc-gnbsim-config
          subPath: example-sample.json
        - mountPath: /dev/net/tun
          name: tun-devdir
        command:
        - sh
      - name: f5gc-gnbsim-probe
        image: nginx:latest
        ports:
        - containerPort: 80
          name: http-probe
          protocol: TCP
      - name: tcpdump
        image: corfr/tcpdump
        imagePullPolicy: IfNotPresent
        command:
        - /bin/sleep
        - infinity
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        runAsGroup: 0
        runAsUser: 0
      serviceAccountName: f5gc-gnbsim-sa
      terminationGracePeriodSeconds: 30
      volumes:
      - configMap:
          name: f5gc-gnbsim-config
        name: f5gc-gnbsim-config
      - hostPath:
          path: /dev/net/tun
        name: tun-devdir
---
---
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition 
metadata:
  name: f5gc-gnbsim-n1n2
spec:
  config: '{ 
      "cniVersion": "0.3.1",
      "type": "macvlan",
      "master": "eno2",
      "mode": "bridge",
      "ipam": {
        "type": "static",
        "addresses": [
                {
                        "address": "172.16.10.10/24",
                        "gateway": "172.16.10.1"
                }
        ]
      }
    }'

---
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: f5gc-gnbsim-n3
spec:
  config: '{
      "cniVersion": "0.3.1",
      "type": "macvlan",
      "master": "eno2",
      "mode": "bridge",
      "ipam": {
        "type": "static",
        "addresses": [
                {
                        "address": "192.168.10.10/24",
                        "gateway": "192.168.10.1"
                }
        ]
      }
    }'
