apiVersion: v1
kind: Service
metadata:
  name: free5gc-udm-svc-pool
  namespace: free5gc
  labels:
    epc-mode: udm
spec:
  selector:
    app: free5gc-udm
  ports:
  - protocol: TCP
    targetPort: 29510
    port: 29504
  selector:
    epc-mode: udm
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: StatefulSet
metadata:
  name: free5gc-udm-deployment
  annotations:
    "cni.projectcalico.org/ipAddrs": "[\"10.244.1.5\"]"
  namespace: free5gc
  labels:
    epc-mode: udm
spec:
  replicas: 1
  serviceName: "free5gc-udm-svc-pool"
  selector:
    matchLabels:
      epc-mode: udm
  template:
    metadata:
      labels:
        epc-mode: udm
    spec:
      containers:
        - name: udm
          image: monandkey/free5gc-udm:3.0.4
          imagePullPolicy: IfNotPresent
          command: ["./udm"]
          volumeMounts:
          - name: free5gc-udm-config
            mountPath: /free5gc/config-map/udmcfg.conf
            subPath: "udmcfg.conf"
          - name: free5gc-udm-free5gc-config
            mountPath: /free5gc/config-map/free5gc.conf
            subPath: "free5gc.conf"
      volumes:
        - name: free5gc-udm-config
          configMap:
            name: free5gc-udm-config
        - name: free5gc-udm-free5gc-config
          configMap:
            name: free5gc-udm-free5gc-config