apiVersion: v1
kind: Service
metadata:
  name: free5gc-nssf-svc-pool
  namespace: free5gc
  labels:
    epc-mode: nssf
spec:
  selector:
    app: free5gc-nssf
  ports:
  - protocol: TCP
    targetPort: 29510
    port: 29510
  selector:
    epc-mode: nssf
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: StatefulSet
metadata:
  name: free5gc-nssf-deployment
  annotations:
    "cni.projectcalico.org/ipAddrs": "[\"10.244.1.3\"]"
  namespace: free5gc
  labels:
    epc-mode: nssf
spec:
  replicas: 1
  serviceName: "free5gc-nssf-svc-pool"
  selector:
    matchLabels:
      epc-mode: nssf
  template:
    metadata:
      labels:
        epc-mode: nssf
    spec:
      containers:
        - name: nssf
          image: monandkey/free5gc-nssf:3.0.4
          imagePullPolicy: IfNotPresent
          command: ["./nssf"]
          volumeMounts:
          - name: free5gc-nssf-config
            mountPath: /free5gc/config-map/nssfcfg.conf
            subPath: "nssfcfg.conf"
          - name: free5gc-nssf-free5gc-config
            mountPath: /free5gc/config-map/free5gc.conf
            subPath: "free5gc.conf"
      volumes:
        - name: free5gc-nssf-config
          configMap:
            name: free5gc-nssf-config
        - name: free5gc-nssf-free5gc-config
          configMap:
            name: free5gc-nssf-free5gc-config