apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: open5gs-mongodb
spec:
  serviceName: open5gs-mongodb
  selector:
    matchLabels:
      app: open5gs-mongodb
  replicas: 1
  template:
    metadata:
      labels:
        app: open5gs-mongodb
    spec:
      securityContext:
        runAsUser: 0
        runAsGroup: 0
      containers:
      - name: mongodb
        image: mongo:4.2.7
        imagePullPolicy: IfNotPresent
        ports:
        - name: mongodb
          containerPort: 27017
        env:
          - name: MONGO_INITDB_DATABASE
            valueFrom:
              configMapKeyRef:
                name: open5gs-mongodb-config
                key: mongo_initdb_database
