apiVersion: apps/v1
kind: Deployment
metadata:
  name: open5gs-pcrf
  labels:
    app: open5gs-pcrf
spec:
  replicas: 1
  selector:
    matchLabels:
      app: open5gs-pcrf
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: open5gs-pcrf
      annotations:
        k8s.v1.cni.cncf.io/networks: open5gs-pcrf-gx
        cni.projectcalico.org/ipAddrs: "[\"10.244.254.37\"]"
    spec:
      securityContext:
        runAsUser: 0
        runAsGroup: 0
      containers:
        - name: open5gs-pcrf
          image: registry.gitlab.com/infinitydon/registry/open5gs-aio:v1.2.0
          imagePullPolicy: IfNotPresent
          command: ["open5gs-pcrfd", "-c", "/open5gs/config-map/pcrf.yaml"]
          securityContext:
            privileged: false
          volumeMounts:
            - name: open5gs-pcrf-config
              mountPath: /open5gs/config-map/pcrf.yaml
              subPath: "pcrf.yaml"
            - name: open5gs-pcrf-diameter
              mountPath: /open5gs/config-map/diameter-pcrf.conf
              subPath: "diameter-pcrf.conf"
          ports:
            - name: if-gx
              containerPort: 3868
              protocol: TCP
        - name: tcpdump
          image: mobilecore/tcpdump:latest
          imagePullPolicy: IfNotPresent
          command:
            - /bin/sleep
            - infinity
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      serviceAccountName: open5gs-pcrf-sa
      terminationGracePeriodSeconds: 30
      volumes:
        - name: open5gs-pcrf-config
          configMap:
            name: open5gs-pcrf-config
        - name: open5gs-pcrf-diameter
          configMap:
            name: open5gs-pcrf-diameter
