apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: webui
  name: open5gs-webui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webui
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: webui
    spec:
      securityContext:
        runAsUser: 0
        runAsGroup: 0
      containers:
      - name: open5gs-webui
        image: registry.gitlab.com/infinitydon/registry/open5gs-webui:1.2.0
        imagePullPolicy: IfNotPresent
        securityContext:
          privileged: false
        command: ["node", "server/index.js"]
        env:
          - name: DB_URI
            value: mongodb://open5gs-mongodb/open5gs
          - name: NODE_ENV
            value: "production"
        ports:
          - name: open5gs-webui
            containerPort: 3000
            protocol: TCP
      - name: tcpdump
        image: mobilecore/tcpdump
        imagePullPolicy: IfNotPresent
        command:
          - /bin/sleep
          - infinity
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      serviceAccountName: open5gs-webui-sa
      terminationGracePeriodSeconds: 30
