apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-python
spec:
  replicas: 3
  selector:
    matchLabels:
      app: app-python
  template:
    metadata:
      labels:
        app: app-python
    spec:
      containers:
      - image: python:3.8.8
        name: pod-python
        command: ["/bin/sh","-c"]
        args: ["ip a |grep '10.244' > ./ip.html; python -V >> ./ip.html; python -m http.server 80"]
