apiVersion: v1
kind: ConfigMap
metadata:
  name: open5gs-sgw-config
  namespace: open5gs
  labels:
    app: sgw
data:
  sgw.yaml: |
    logger:
        file: /var/log/open5gs/sgw.log
    
    parameter:
        no_ipv6: true
    
    sgw:
        gtpc:
           dev: net1
        gtpu:
           dev: net2
