apiVersion: v1
kind: ConfigMap
metadata:
  name: free5gc-amf-config
  namespace: free5gc
  labels:
    epc-mode: amf
data:
  amfcfg.conf: |
    info:
      version: 1.0.0
      description: AMF initial local configuration
    
    configuration:
      amfName: AMF
      ngapIpList:
        - 10.244.1.1
      sbi:
        scheme: http
        registerIPv4: 10.244.1.1 # IP used to register to NRF
        bindingIPv4: 10.244.1.1  # IP used to bind the service
        port: 29518
      serviceNameList:
        - namf-comm
        - namf-evts
        - namf-mt
        - namf-loc
        - namf-oam
      servedGuamiList:
        - plmnId:
            mcc: 208
            mnc: 93
          amfId: cafe00
      supportTaiList:
        - plmnId:
            mcc: 208
            mnc: 93
          tac: 1
      plmnSupportList:
        - plmnId:
            mcc: 208
            mnc: 93
          snssaiList:
            - sst: 1
              sd: 010203
            - sst: 1
              sd: 112233
      supportDnnList:
        - internet
      nrfUri: http://10.244.1.7:29510
      security:
        integrityOrder:
          - NIA2
          # - NIA0
        cipheringOrder:
          - NEA0
          # - NEA2
      networkName:
        full: free5GC
        short: free
      t3502: 720
      t3512: 3600
      non3gppDeregistrationTimer: 3240
